# orbs: # declare what orbs we are going to use
#   node: circleci/node@2.0.2 # the node orb provides common node-related configuration



version: 2.0 # using 2.1 provides access to orbs and other features

workflows:
  version: 2
  deploy:
    jobs:
      - build:
        filters:
          branches:
            only: 
              - /^config-test/

jobs:
  build:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run: yarn
  build-deploy:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn export
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: out
          to: 's3://simonng.dev'
