# orbs: # declare what orbs we are going to use
#   node: circleci/node@2.0.2 # the node orb provides common node-related configuration

orbs:
   aws-s3: circleci/aws-s3@3.0.0

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  checkout-build:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run: yarn
      - run: yarn:export
  deploy:
    docker: # Use the Docker execut or for the deploy job
      - image: circleci/node:14.17
      - aws-s3/sync:
        from: out
        to: 's3://mercury-photos'
        arguments: | # Optional arguments
          --acl public-read \
          --cache-control "max-age=86400"
        overwrite: true # default is false


workflows:
  build:
    jobs:
      - checkout-build
      - deploy
